### ISSUE TITLE
Opravit odkazy a způsob stažení pracovních dat v Agregace a spojování

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/python-data-1#14]
V Agregace a spojování [1] aktualizovat stažení pracovních dat:
```
r = requests.get("https://kodim.cz/czechitas/progr2-python/python-pro-data-1/agregace-a-spojovani/assets/u202.csv")
open("u202.csv", "wb").write(r.content)
```
a nahradit přímo za za:
```
pandas.read_csv(url)
```
podle [2]

[1] https://kodim.cz/kurzy/python-data-1/python-pro-data-1/agregace-a-spojovani
[2] https://stackoverflow.com/questions/32400867/pandas-read-csv-from-url

**Comment by ZelenyMartin** [comment]
```
pandas.read_csv("https://kodim.cz/cms/assets/kurzy/python-data-1/python-pro-data-1/agregace-a-spojovani/u202.csv")
```
funguje

**Comment by lutydlitatova** [comment]
To vypadá dobře, máme to ověřené, že to bude bez problémů i na Windows? @pesikj

**Comment by lutydlitatova** [comment]
Dále by se to dalo upravit tady ve cvičeních
* [studenti](https://github.com/lutydlitatova/python-data-1/blob/main/python-pro-data-1/agregace-a-spojovani/excs/studenti/exercise.md?plain=1#L11) 
* [call centrum ](https://github.com/lutydlitatova/python-data-1/blob/main/python-pro-data-1/vizualizace/excs/call-centrum/exercise.md?plain=1#L14) (Vizualizace)
* [kostky](https://github.com/lutydlitatova/python-data-1/blob/main/python-pro-data-1/vizualizace/excs/hazeni-kostkami/exercise.md?plain=1#L16) (Vizualizace)

A případně v domácích úkolech (to nejde na web, takže to je asi méně důležité)
