### ISSUE TITLE
Sloučit stránku Instalace jazyka Python a editoru Visual Studio Code a Instalace modulů

### ISSUE THREAD

**Issue by pesikj** [Czechitas-Python/python-data-1#29]
Bohužel jsme zjistili, že z té stránky spousta lidí nepochopila, že je potřeba doinstalovat i moduly. Navíc ta instalace jazyka je cca na 3 řádky, takže to nemusí mít samostatnou stránku.

@lutydlitatova Prosím o schválení :-)

**Comment by ZelenyMartin** [comment]
Souhlasim. Urcite vse na jedne strance.

**Comment by lutydlitatova** [comment]
Jsem pro!
