### ISSUE TITLE
Přesunout cvičení na Regulární výrazy na samostatné stránky

### ISSUE THREAD

**Issue by AnetaPopelova** [Czechitas-Python/python-data-1#48]
Cvičení jsou kapitol `Regulární výrazy` a `Regulární výrazy v Pythonu` jsou navzdory ustálené praxi v ostatních kapitolách umístěné přímo pod výkladem. 

@pesikj

**Comment by ZelenyMartin** [comment]
Já bych byl, prosím, pro to nechat to tak. S Jirkou jsme se shodli na následujícím:
* Pokud je výklad před samostatným cvičením rozdělen do více sekcí (stránek), cvičení dáme do samostatné sekce.
* Pokud je výklad jen v jedné sekci (stránce), necháme cvičení na konci této stránky, tak aby pro nápovědu stačilo jednoduše odscrollovat nahoru.

Je to tak pro tebe ok? Díky.

**Comment by AnetaPopelova** [comment]
OK - rozumim, chapu.
