### ISSUE TITLE
Úpravy v rozvržení kapitol _Načtení dat_, _Základní dotazy_ a _Agregace a spojování_ pro 3h bloky

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/python-data-1#49]
Naposledy jsem ve dvou 3h blocích (v rozvrhu Pandas 1 a Pandas 2) učil tyto tři kapitoly:

- nacteni-dat
- zakladni-dotazy
- agregace-a-spojovani

Budem to nějak revidovat do dvou kapitol včetně lepší návaznosti cvičení na látku?

**Comment by pesikj** [comment]
Já bych byl pro rozdělení agregací do dvou části, je to poměrně dlouhé.

**Comment by ZelenyMartin** [comment]
Navrhuji _Nacteni dat_ https://kodim.cz/kurzy/python-data-1/python-pro-data-1/nacteni-dat/nacteni-dat a prvni strana ze _Zakladni dotazy_ https://kodim.cz/kurzy/python-data-1/python-pro-data-1/zakladni-dotazy/zakladni-dotazy dat do stejne kapitoly (pracovni nazev Pandas 1)... minule mi to presne vyslo na 3h blok. Bude to v DA povinna lekce.

Blok Pandas 2 by byl _Podmineny vyber_ https://kodim.cz/kurzy/python-data-1/python-pro-data-1/zakladni-dotazy/podmineny-vyber a _Agregace a spojovani_ https://kodim.cz/kurzy/python-data-1/python-pro-data-1/agregace-a-spojovani/agregace-a-spojovani - v DA volitelna lekce.

Jak chces rozdelovat _Agregace a spojování_?

**Comment by pesikj** [comment]
> Navrhuji Nacteni dat https://kodim.cz/kurzy/python-data-1/python-pro-data-1/nacteni-dat/nacteni-dat a prvni strana ze Zakladni dotazy https://kodim.cz/kurzy/python-data-1/python-pro-data-1/zakladni-dotazy/zakladni-dotazy dat do stejne kapitoly (pracovni nazev Pandas 1)... minule mi to presne vyslo na 3h blok. Bude to v DA povinna lekce.

Soulasím

> Jak chces rozdelovat Agregace a spojování?

Vytvořit bych samostatnou kapitolu od začátku až po konec Spojení dat a druhou kapitolu od Spojení dat do konce.

**Comment by ZelenyMartin** [comment]
> Vytvořit bych samostatnou kapitolu od začátku až po konec Spojení dat a druhou kapitolu od Spojení dat do konce.

Jo - nova sekce. To zni dobre.

**Comment by ZelenyMartin** [comment]
Kapitola _Agregace a spojování_ rozdělena.
