### ISSUE TITLE
Lepší cvičení pro prozkoumávání dat, než Nabídky práce

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/python-data-1#55]
https://kodim.cz/kurzy/python-data-1/python-pro-data-1/nacteni-dat/excs#excs%3Enabidky

- [x] Pro první cvičení v pandas použít čistší a menší dataset
- [x] Odstranit použití `iloc[]`

**Comment by pesikj** [comment]
Souhlasím

**Comment by ZelenyMartin** [comment]
Ten dataset [DataAnalyst.csv](https://kodim.cz/cms/assets/kurzy/python-data-1/python-pro-data-1/nacteni-dat/excs/excs%3Enabidky/DataAnalyst.csv) má z mého pohledu pár problému pro začátečníky:

* Ten první sloupec obsahuje index a nemá vyplněnou hlavičku
* Je tam buňka s multiline textem

Nenahradíme to tím klasickým Titanic Passengers datasetem, který se používá ve všech úvodních tutoriálech?

**Comment by pesikj** [comment]
Ano, jsem pro.
