### ISSUE TITLE
Zvážit kompletní přesun `iloc[]` a `loc[]` do čtení na doma + úpravy

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/python-data-1#56]
- [x] https://kodim.cz/kurzy/python-data-1/python-pro-data-1/nacteni-dat/cisla-radku Podle mě je to okrajové a nedává to smysl na první Pandas lekci. Mnohem užitečnější je brát dřív podmíněný výběr.
    * Upravit navázaná cvičení
- [x] Předělat https://kodim.cz/kurzy/python-data-1/python-pro-data-1/nacteni-dat/indexy
    * Jako pojmenovaný index zvolit zkratku státu (ne celý název)
- [x] https://kodim.cz/kurzy/python-data-1/python-pro-data-1/nacteni-dat/indexy#excs%3Eceska-jmena - odstranit diakritiku z hlavičky dat

**Comment by ZelenyMartin** [comment]
Nahradit

`staty = staty.set_index("name")` za

`staty.set_index("name", inplace=True)`

**Comment by pesikj** [comment]
Souhlas
