### ISSUE TITLE
Dovysvetlit v lekci na regexpy jak funguje re.findall nad grupami

### ISSUE THREAD

**Issue by pavelsuk** [Czechitas-Python/python-data-1#59]
V lekci na [regularni vyrazy](https://kodim.cz/kurzy/python-data-1/ziskavani-dat/regularni-vyrazy/python-re) je zminena metoda `re.findall`, ktera ale nefunguje uplne intuitivne pri pouziti group.

Bylo by fajn mozny problem a jeho reseni v lekci aspon naznacit, podobne jako @AnetaPopelova pri lekci (credit @soustruh)

```
# re.findall tries to match captures groups (i.e. the portions of the regex that are enclosed in parentheses), 
# then it is the groups that are returned, rather than the matched string.
# One way to solve this issue is to use non-capturing groups (prefixed with ?:).

# regularni_vyraz = re.compile(r"(\+420)? ?\d{3} ?\d{3} ?\d{3}") # vraci jen "+420"
# regularni_vyraz = re.compile(r"(?:\+420)? ?\d{3} ?\d{3} ?\d{3}") # vraci cele cislo
```

**Comment by ZelenyMartin** [comment]
Ty skupiny se tam probírají velmi okrajově a ne v souvislosti s `findall()`. Tu non-capturing group vidím asi poprvé a nikdy jsem se zatím s takovým problémem nesetkal. Je to hodně pokročilé a myslím, že to nemá smysl na lekci vůbec řešit. Zbytečně by se text zamotal, a kdo sám narazí na takto složitý problém, musí si to vygooglit.

**Comment by ZelenyMartin** [comment]
@pavelsuk navrhuješ nějakou konkrétní úpravu textu? Doufám, že `findall()` s grupami se tam nikde nemusí použít. Já nevím, co bych k tomu řekl, aby se to zbytečně nezkomplikovalo. Navrhuji zavřít issue.

**Comment by pavelsuk** [comment]
Jestli se na to bezne pri vyuce nenarazi, tak to klidne zavreme
