### ISSUE TITLE
Smazat odstavec o instalaci Pythonu s odkazy

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/python-data-1#67]
Neni to relevatni, Python uz musi mit nainstalovany.

https://github.com/Czechitas-Python/python-data-1/blob/696d6d1f7f4177a32bb4cd874bc8fecb71053ad1/python-pro-data-1/instalace/instalace-modulu.md?plain=1#L1-L6

**Comment by lutydlitatova** [comment]
Po diskuzi odstavec necháme.
