### ISSUE TITLE
Vysledek kodu na strance Propojeni Dat neodpovida obsahu promenne, pokud jdu v lekci postupne 

### ISSUE THREAD

**Issue by pavelsuk** [Czechitas-Python/python-data-1#74]
Na strance [Propojeni Dat](https://kodim.cz/analyza-dat/python-data-1/python-pro-data-1/agregace-a-spojovani/propojeni-dat), priklad

```
propojeny_df = pandas.merge(u202, studenti)
print(propojeny_df.head())  
```
je ukazany vysledek s tim, ze `u202` tam obsahuje i ten prvni radek bez znamky. Kdyz ale jdu v lekci postupne, tak uz jsme ho na predchozi strance odstranili pres dropna.

**Navrhovane reseni:**

Opravit vystup podle skutecneho obsahu.

**Comment by ZelenyMartin** [comment]
Navrhuji tady místo s dataframem `u202` pracovat s `maturita`, který byl vytvořen v předchozí části lekce.

**Comment by ZelenyMartin** [comment]
@pavelsuk ahoj, @pesikj psal, že chce celý pandas kurz předělat do práce s jiným datasetem, tak už bych neřešil dílčí změny do tohoto textu. Navrhuji zavřít issue.

**Comment by pesikj** [comment]
Souhlasím, už tomu nevěnujme čas. Přepíšu to snad během prodlouženého víkendu.
