### ISSUE TITLE
Stranky Agregace a Pocitane Sloupce predpokladaji, ze lekce se jedou na jeden zatah - od Nacitani dat   

### ISSUE THREAD

**Issue by pavelsuk** [Czechitas-Python/python-data-1#75]
Na strance [Agregace](https://kodim.cz/analyza-dat/python-data-1/python-pro-data-1/agregace-a-spojovani/agregace) je uplne na konci navaznost na priklad s nakupy, ktery se pouzival v minule lekci. Pokud je vyuka rozdelena na dve casti s casovym odstupem (viz DA), nemusi to uplne davat smysl.

Podobne je to i na strance [Pocitane sloupce](https://kodim.cz/analyza-dat/python-data-1/python-pro-data-1/agregace-a-spojovani/ruzne), kde se pouziva soubor [staty.json](https://kodim.cz/cms/assets/analyza-dat/python-data-1/python-pro-data-1/podmineny-vyber/podmineny-vyber/staty.json)

**Mozne reseni**: 

Dat do teto sekce odkaz na tu minulou lekci, pripadne i na to, kde stahnout ten soubor ([nakupy.csv](https://kodim.cz/cms/assets/analyza-dat/python-data-1/python-pro-data-1/nacteni-dat/nacteni-dat/nakupy.csv), [staty.json](https://kodim.cz/cms/assets/analyza-dat/python-data-1/python-pro-data-1/podmineny-vyber/podmineny-vyber/staty.json))

**Comment by ZelenyMartin** [comment]
Tu ukazku s nakupy bych celou smazal. Bohate staci ukazat groupovani na te maturite.

**Comment by pavelsuk** [comment]
> Tu ukazku s nakupy bych celou smazal. Bohate staci ukazat groupovani na te maturite.

Navic je ten kod s nakupy spatne, nesedi tam nazvy sloupecku

**Comment by ZelenyMartin** [comment]
@pavelsuk ahoj, @pesikj psal, že chce celý pandas kurz předělat do práce s jiným datasetem, tak už bych neřešil dílčí změny do tohoto textu. Navrhuji zavřít issue.

**Comment by pesikj** [comment]
Souhlasím, už tomu nevěnujme čas. Přepíšu to snad během prodlouženého víkendu.
