### ISSUE TITLE
Předělat cvičení na scraping kodim.cz

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/python-data-1#77]
Cvičení na scraping kodim.cz se v této podobě už nedá snadno realizovat. Navrhuji smazat, nebo významně zobecnit, aby nebyl dán požadovaný výstup.

https://kodim.cz/analyza-dat/python-data-1/ziskavani-dat/webscraping/webscraping/scraping-kodim.cz
https://github.com/Czechitas-Python/python-data-1/blob/main/ziskavani-dat/webscraping/excs/scraping-kodim.cz.md

**Comment by pesikj** [comment]
Navrhuji spíše smazat.
