### ISSUE TITLE
Revize kap. Regulární výrazy

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/python-data-1#78]
* Zdůraznit skupiny a možnost kvantifikátoru skupiny (tento odstavec)
> Pokud potřebujeme zajistit opakování určité sekvence znaků (ne jen jednoho), můžeme sekvenci znaků uzavřít do kulatých závorek ( ) a za pravou závorku umístit kvantifikátor. Pokud máme variant více, můžeme k jejich oddělení použít znak |. Například pokud chceme vybrat oba víkendové dny, napíšeme (sobota|neděle).

* Rozsahy `[a-z]` umístit rovnou za množiny znaků `[]`, ukázat více rozsahů v jedné množině `[a-zA-Z0-9]`
* Smazat ukázku `magicka_konstanta` - není to tak klíčové a obecně je tam už ukázek dost
* Smazat nebo lépe vysvětlit cvičení Nápravy (nerozumím tomu moc) https://kodim.cz/analyza-dat/python-data-1/ziskavani-dat/regularni-vyrazy/regularni-vyrazy/napravy
* Kdyby se náhodou podařilo, tak zkusit nějakou lepší úvodní ukázku dat než lístek kurzů ve směnárně. Nezdá se mi tam na první pohled jasný smysl regexů. Nevím ale co tam dát.

Odkaz na kapitolu: https://kodim.cz/analyza-dat/python-data-1/ziskavani-dat/regularni-vyrazy/regularni-vyrazy

**Comment by pesikj** [comment]
Souhlasím.
