### ISSUE TITLE
Úklid v branchich

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/python-data-1#8]
Pokud příjde někdo nový s PR, měl by jednoduše vědět kam dávat PR, tj. do `main`. Taky je nehezké forkovat si repo s více stale branchama. Proto navrhuji:

1. přejmenovat `master` na např. `legacy` (je to už formát nekompatibilní s aktuálním kodim.cz)
2. větev `stage` rovnou smazat.

**Comment by lutydlitatova** [comment]
Hotovo ✔️
